"use client";

import React from "react";
import { Button } from "./ui/button";

interface WrapperProps {
  children: React.ReactNode;
  className?: string;
}

export const Wrapper = ({ children, className }: Readonly<WrapperProps>) => {
  return (
    <div className={`${className} max-w-[80rem] w-full mx-auto `}>
      {children}
    </div>
  );
};

interface FormWrapperProps {
  title: string;
  description?: string;
  children: React.ReactNode;
  onSubmit: (e: React.FormEvent) => void;
  isSubmitting?: boolean;
}

/**
 * Form wrapper component for consistent form styling and layout
 * Provides a card-like container with a title, description, and consistent styling
 * Generated by Copilot
 */
export const FormWrapper = ({
  title,
  description,
  children,
  onSubmit,
  isSubmitting = false,
}: FormWrapperProps) => {
  return (
    <div className="bg-white rounded-none shadow-md p-6 md:p-10 max-w-5xl mx-auto">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900">{title}</h1>
        {description && (
          <p className="mt-3 text-gray-600 text-sm">{description}</p>
        )}
      </div>

      <form onSubmit={onSubmit} className="space-y-12">
        {children}

        <div className="flex justify-end gap-4">
          <Button
            type="button"
            className="px-4 py-2 border border-gray-300 rounded-none shadow-sm text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 text-sm"
            onClick={() => window.history.back()}
          >
            Cancel
          </Button>

          <Button
            type="submit"
            disabled={isSubmitting}
            className={`px-4 py-2 border border-transparent rounded-none shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 text-sm ${
              isSubmitting ? "opacity-70 cursor-not-allowed" : ""
            }`}
          >
            {isSubmitting ? "Saving..." : "Save Product"}
          </Button>
        </div>
      </form>
    </div>
  );
};
