import React from "react";

/**
 * ResponsiveLazyImage component for advanced responsive image loading
 * - Uses srcset for different image resolutions
 * - Automatically selects appropriate image based on viewport and device
 * - Supports art direction with different image formats
 * - Generated by Copilot
 */

interface LazyImageProps {
  src: string;
  alt?: string;
  className?: string;
  width?: number | string;
  height?: number | string;
  sizes?: string;
  srcset?: string; // Multiple resolution options
}
const ResponsiveLazyImage = ({
  srcset,
  src,
  alt,
  className,
  width,
  height,
  sizes = "100vw",
}: LazyImageProps) => {
  // Use React's loading="lazy" for native lazy loading instead of a custom solution
  return (
    <img
      className={`max-w-full h-auto ${className || ""}`} // Ensure images are responsive by default
      src={src} // Direct source instead of placeholder
      srcSet={srcset} // Use standard srcSet (with capital S)
      sizes={sizes}
      width={width}
      height={height}
      alt={alt || ""}
      loading="lazy" // Native lazy loading
      onError={(e) => {
        // Handle image loading errors gracefully
        e.currentTarget.src = "/images/placeholder.png"; // Fallback to a placeholder image
      }}
    />
  );
};

export default ResponsiveLazyImage;
