import React from "react";

/**
 * ResponsiveLazyImage component for advanced responsive image loading
 * - Uses srcset for different image resolutions
 * - Automatically selects appropriate image based on viewport and device
 * - Supports art direction with different image formats
 * - Generated by Copilot
 */

interface LazyImageProps {
  src: string;
  alt?: string;
  className?: string;
  width?: number | string;
  height?: number | string;
  sizes?: string;
  srcset?: string; // Multiple resolution options
}
const ResponsiveLazyImage = ({
  srcset,
  src,
  alt,
  className,
  width,
  height,
  sizes = "100vw",
}: LazyImageProps) => {
  const placeholderSrc =
    "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";

  return (
    <img
      className={`lazyload ${className || ""}`}
      src={placeholderSrc}
      data-srcset={srcset} // Multiple resolution options
      data-src={src} // Fallback src
      data-sizes={sizes} // Could be "auto" or custom sizes
      width={width}
      height={height}
      alt={alt || ""}
    />
  );
};

export default ResponsiveLazyImage;
