"use client";

import { useState } from "react";

import { Plus } from "lucide-react";
import Modal from "./modal";
import { ColorData } from "@/-database/db";
import { Button } from "./ui/button";

interface ColorPickerProps {
  colors: string[];
  onAddColor: (color: string) => void;
  onDeleteColor: (color: string) => void;
  error?: string;
}

/**
 * Color picker component for selecting product colors
 * Allows selecting from predefined colors or adding custom hex colors
 * Generated by Copilot
 */
export const FormColors = ({
  colors,
  onAddColor,
  onDeleteColor,
  error,
}: ColorPickerProps) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [customColor, setCustomColor] = useState("#000000");
  const [colorError, setColorError] = useState("");

  // Open color picker modal
  const openModal = () => setIsModalOpen(true);

  // Close color picker modal
  const closeModal = () => setIsModalOpen(false);

  // Validate hex color code format
  const isValidHexColor = (color: string) => {
    return /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(color);
  };

  // Add custom color after validation
  const addCustomColor = () => {
    if (!isValidHexColor(customColor)) {
      setColorError("Please enter a valid hex color code (e.g., #FF0000)");
      return;
    }

    onAddColor(customColor);
    setCustomColor("#000000");
    setColorError("");
    closeModal();
  };

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <h3 className="text-sm font-semibold text-gray-800">Product Colors</h3>
        <Button
          type="button"
          onClick={openModal}
          className="flex items-center gap-2 px-4 py-2 bg-blue-50 text-blue-600 rounded-none hover:bg-blue-100 transition-colors text-sm"
        >
          <Plus size={16} />
          <span>Add Custom Color</span>
        </Button>
      </div>

      {error && <p className="text-red-500 text-sm">{error}</p>}

      <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
        {/* Predefined color options for phone accessories - covers popular color preferences */}
        {ColorData.map((color) => (
          <button
            key={color.value}
            type="button"
            onClick={() => onAddColor(color.value)}
            className="flex flex-col items-center space-y-2 p-3 rounded-none hover:bg-gray-50 transition-colors"
          >
            <div
              className="w-10 h-10 rounded-full border border-gray-200"
              style={{ backgroundColor: color.value }}
            />
            <span className="text-sm text-gray-700">{color.label}</span>
          </button>
        ))}
      </div>

      {/* Selected colors display */}
      {colors.length > 0 && (
        <div className="mt-6">
          <h4 className="text-sm font-medium text-gray-700 mb-3">
            Selected Colors
          </h4>
          <div className="flex flex-wrap gap-3">
            {colors.map((color) => (
              <div key={color} className="group relative">
                <div
                  className="w-10 h-10 rounded-full border border-gray-200 cursor-pointer"
                  style={{ backgroundColor: color }}
                  title={color}
                />
                <Button
                  type="button"
                  onClick={() => onDeleteColor(color)}
                  className="absolute -top-2 -right-2 bg-white rounded-none w-5 h-5 flex items-center justify-center text-red-500 border border-gray-200 opacity-0 group-hover:opacity-100 transition-opacity text-sm"
                  aria-label={`Remove ${color}`}
                >
                  &times;
                </Button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Modal for custom color */}
      {isModalOpen && (
        <Modal onClose={closeModal}>
          <div className="space-y-4 p-6">
            <h2 className="text-xl font-semibold text-gray-800">
              Add Custom Color
            </h2>
            <p className="text-sm text-gray-600">
              Enter a valid hex color code (e.g., #FF0000).
            </p>

            {/* Color Preview for visual feedback before adding */}
            <div
              className="w-full h-20 rounded-none border border-gray-200"
              style={{ backgroundColor: customColor || "#FFFFFF" }}
            />

            {/* Custom Color Input with hex validation */}
            <input
              type="text"
              value={customColor}
              onChange={(e) => setCustomColor(e.target.value)}
              placeholder="#000000"
              className="w-full p-3 border border-gray-200 rounded-none text-sm"
            />

            {colorError && <p className="text-red-500 text-sm">{colorError}</p>}

            <div className="flex justify-end space-x-3 mt-6">
              <Button
                type="button"
                onClick={closeModal}
                className="px-4 py-2 border border-gray-300 rounded-none shadow-sm text-sm"
              >
                Cancel
              </Button>
              <Button
                type="button"
                onClick={addCustomColor}
                className="px-4 py-2 border border-transparent rounded-none shadow-sm text-white text-sm"
              >
                Add Color
              </Button>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
};
